#!/usr/bin/env bash
# Pings the ip passed as argument 5 times or prints "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" if no argument is passed.
if [[ -z "$1" ]]
then
    echo "Usage: $(basename "$0") {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
